<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Re: <?= $contact->subject->safe ?></title>
</head>
<body style="background-color:#eee">
    <div style="background-color:white;margin:20px auto;max-width:750px;padding:50px;">
        <div style="margin-bottom:20px;"><?= $contact->reply ?></div>

        <div style="background-color:rgba(0,0,0,.05);padding:40px;">
            <h3 style="margin-top:0;"><?= $contact->subject->safe ?></h3>
            <p><?= nl2br($contact->content->safe) ?></p>
        </div>

        <hr>

        <div style="text-align:center">
            <?= date('Y') ?> &middot; <?= \Mim::$app->config->name ?>
        </div>
    </div>
</body>
</html>